Our ntp isn't patched to drop privileges.

--- a/ipa-client/ipaclient/ntpconf.py
+++ b/ipa-client/ipaclient/ntpconf.py
@@ -147,7 +147,7 @@ def synconce_ntp(server_fqdn):
     if os.path.exists(ntpdate):
         # retry several times -- logic follows /etc/init.d/ntpdate
         # implementation
-        cmd = [ntpdate, "-U", "ntp", "-s", "-b", "-v", server_fqdn]
+        cmd = [ntpdate, "-s", "-b", "-v", server_fqdn]
         for retry in range(0, 3):
             try:
                 ipautil.run(cmd)
